# Generated by Django 4.2.4 on 2024-01-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('contact', models.IntegerField()),
                ('city', models.CharField(max_length=49)),
                ('email', models.EmailField(max_length=49)),
            ],
        ),
    ]
